# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Imgui_config = debug
  VilagOS_config = debug
  Game_config = debug
endif
ifeq ($(config),release)
  Imgui_config = release
  VilagOS_config = release
  Game_config = release
endif
ifeq ($(config),dist)
  Imgui_config = dist
  VilagOS_config = dist
  Game_config = dist
endif

PROJECTS := Imgui VilagOS Game

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Imgui:
ifneq (,$(Imgui_config))
	@echo "==== Building Imgui ($(Imgui_config)) ===="
	@${MAKE} --no-print-directory -C VilagOS/vendor/Imgui -f Makefile config=$(Imgui_config)
endif

VilagOS: Imgui
ifneq (,$(VilagOS_config))
	@echo "==== Building VilagOS ($(VilagOS_config)) ===="
	@${MAKE} --no-print-directory -C VilagOS -f Makefile config=$(VilagOS_config)
endif

Game: VilagOS
ifneq (,$(Game_config))
	@echo "==== Building Game ($(Game_config)) ===="
	@${MAKE} --no-print-directory -C Game -f Makefile config=$(Game_config)
endif

clean:
	@${MAKE} --no-print-directory -C VilagOS/vendor/Imgui -f Makefile clean
	@${MAKE} --no-print-directory -C VilagOS -f Makefile clean
	@${MAKE} --no-print-directory -C Game -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Imgui"
	@echo "   VilagOS"
	@echo "   Game"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"