#pragma once

#define VOS_MOUSE_BUTTON_1         0
#define VOS_MOUSE_BUTTON_2         1
#define VOS_MOUSE_BUTTON_3         2
#define VOS_MOUSE_BUTTON_4         3
#define VOS_MOUSE_BUTTON_5         4
#define VOS_MOUSE_BUTTON_6         5
#define VOS_MOUSE_BUTTON_7         6
#define VOS_MOUSE_BUTTON_8         7
#define VOS_MOUSE_BUTTON_LAST      VOS_MOUSE_BUTTON_8
#define VOS_MOUSE_BUTTON_LEFT      VOS_MOUSE_BUTTON_1
#define VOS_MOUSE_BUTTON_RIGHT     VOS_MOUSE_BUTTON_2
#define VOS_MOUSE_BUTTON_MIDDLE    VOS_MOUSE_BUTTON_3